name: CI - Spring Boot + Flyway + PostgreSQL + Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.ENV_POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.ENV_ROOT_PASSWORD }}
          POSTGRES_DB: postgres_learning_dev_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.ENV_POSTGRESQL_USER }} -d postgres_learning_dev_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: setup Java 17 and cache Maven
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: build project and run tests
      - name: Build and Run Maven Tests
        env:
          POSTGRES_USER: ${{ secrets.ENV_POSTGRESQL_USER}}
          POSTGRES_PASSWORD: ${{ secrets.ENV_ROOT_PASSWORD }}
          POSTGRES_DB: postgres_learning_dev_db
        run: mvn clean verify

